CREATE TYPE "conversationType" AS ENUM (
  'single',
  'group'
);

CREATE TABLE "Users" (
  "id" INT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  "firstname" varchar(50) NOT NULL,
  "lastname" varchar(50) NOT NULL,
  "email" varchar(50) UNIQUE NOT NULL,
  "avatar" varchar DEFAULT 'https://cdn.pixabay.com/photo/2015/10/05/22/37/blank-profile-picture-973460_1280.png',
  "password" varchar NOT NULL,
  "description" varchar(120),
  "validEmail" boolean DEFAULT false,
  "createdAt" timestamp,
  "updatedAt" timestamp
);

CREATE TABLE "Conversations" (
  "id" INT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  "title" varchar(30),
  "ConversationImage" varchar DEFAULT 'https://icons.iconarchive.com/icons/custom-icon-design/silky-line-user/512/users-icon.png',
  "type" conversationType DEFAULT 'single',
  "createdAt" timestamp,
  "createdBy" int NOT NULL
);

CREATE TABLE "Messages" (
  "id" INT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  "content" text NOT NULL,
  "createdAt" timestamp,
  "senderId" int NOT NULL,
  "conversartionId" int NOT NULL
);

CREATE TABLE "Participants" (
  "userId" int NOT NULL,
  "conversartionId" int NOT NULL
);

ALTER TABLE "Messages" ADD FOREIGN KEY ("senderId") REFERENCES "Users" ("id");

ALTER TABLE "Messages" ADD FOREIGN KEY ("conversartionId") REFERENCES "Conversations" ("id");

ALTER TABLE "Conversations" ADD FOREIGN KEY ("createdBy") REFERENCES "Users" ("id");

ALTER TABLE "Participants" ADD FOREIGN KEY ("userId") REFERENCES "Users" ("id");

ALTER TABLE "Participants" ADD FOREIGN KEY ("conversartionId") REFERENCES "Conversations" ("id");
